export const policiesStrips=[
    {
        title:'Agents Status',
        totalData:{title:'Total',count:191,itemStatus:'increase'},
        stripItems:[
            {
                title:'Active',
                count:123,
                color:'#288718'
            },
            {
                title:'Inactive',
                count:52,
                color:'#9E9E9E'
            },
            {
                title:'Active with error',
                count:88,
                color:'#FF7A00'
            },
        ]
    },
    {
        title:'Alert by OS',
        stripItems:[
            {
                title:'Apple',
                count:30,
                color:'#57C1EE',
                icon:'apple.png'
            },
            {
                title:'Microsoft',
                count:30,
                color:'#D5A0FF',
                icon:'windows.png'
            },
            {
                title:'Linux',
                count:30,
                color:'#9256DE',
                icon:'snap.png'
            },
        ]
    },
    {
        title:'Alerts by environment',
        stripItems:[
            {
                title:'Safari',
                count:30,
                color:'#57C1EE',
                icon:'safari.png'
            },
            {
                title:'Chrome',
                count:30,
                color:'#D5A0FF',
                icon:'chrome.png'
            },
            {
                title:'Fire fox',
                count:30,
                color:'#9256DE',
                icon:'firefox.png'
            },
        ]
    }
];
export const alertsStrips=[
    {
        title:'Accounts by Posture',
        totalData:{title:'Total',count:7},
        stripItems:[
            {
                title:'Critical',
                count:2,
                color:'#FF275B'
            },
            {
                title:'Medium',
                count:3,
                color:'#FF7A00'
            },
            {
                title:'Low',
                count:2,
                color:'#6C85E6'
            },
        ]
    },
    {
        title:'Top Accounts By Alert',
        totalData:{title:'Total',count:123,itemStatus:'increase'},
        stripItems:[
            {
                title:'Walmart',
                count:30,
                color:'#FFFFFF',
                icon:'wallmart.png'
            },
            {
                title:'Amazon',
                count:27,
                color:'#C4C4C4',
                icon:'amazon.png'
            },
            {
                title:'Target',
                count:20,
                color:'#9E9E9E',
                icon:'target.png'
            },
            {
                title:'DropBox',
                count:20,
                color:'#6A6A6A',
                icon:'dropbox.png'
            },
            {
                title:'Monday',
                count:20,
                color:'#4C4C4D',
                icon:'monday.png'
            },
        ]
    },
];
