export const policiesStrips=[
    {
        title:'Agents Status',
        totalData:{title:'Total',count:191,itemStatus:'increase'},
        stripItems:[
            {
                title:'Active',
                count:123,
                color:'#288718'
            },
            {
                title:'Inactive',
                count:52,
                color:'#9E9E9E'
            },
            {
                title:'Active with error',
                count:88,
                color:'#FF7A00'
            },
        ]
    },
    {
        title:'Alert by OS',
        stripItems:[
            {
                title:'Apple',
                count:30,
                color:'#57C1EE',
                icon:'apple.png'
            },
            {
                title:'Microsoft',
                count:30,
                color:'#D5A0FF',
                icon:'windows.png'
            },
            {
                title:'Linux',
                count:30,
                color:'#9256DE',
                icon:'snap.png'
            },
        ]
    },
    {
        title:'Alerts by environment',
        stripItems:[
            {
                title:'Safari',
                count:30,
                color:'#57C1EE',
                icon:'safari.png'
            },
            {
                title:'Chrome',
                count:30,
                color:'#D5A0FF',
                icon:'chrome.png'
            },
            {
                title:'Fire fox',
                count:30,
                color:'#9256DE',
                icon:'firefox.png'
            },
        ]
    }
];
